services:
  # High-Performance Django Application
  web:
    build: .
    command: gunicorn campshub360.wsgi:application --config gunicorn.conf.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=campshub360.production
      - POSTGRES_DB=campushub360
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - GUNICORN_WORKERS=4
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=1000
      - RATE_LIMIT_RPM=1000
      - RATE_LIMIT_BURST=100
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=campushub360
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_files:/app/staticfiles
      - media_files:/app/media
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_files:
  media_files:
