version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: campushub360:latest
    command: ./run-gunicorn.sh
    environment:
      - DJANGO_SETTINGS_MODULE=campshub360.settings
      - DEBUG=False
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=1000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=campushub360
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:


