# Generated by Django 5.2.5 on 2025-09-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campshub360', '0001_outbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outbox',
        ),
    ]
